DROP ALL OBJECTS;
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa_ratings (
    id INTEGER PRIMARY KEY,
    code VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL CHECK (duration > 0),
    mpa_rating_id INTEGER NOT NULL,
    FOREIGN KEY (mpa_rating_id) REFERENCES mpa_ratings(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT,
    genre_id INTEGER,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_film_genre_film_id ON film_genre (film_id);

CREATE TABLE IF NOT EXISTS film_likes (
    film_id BIGINT,
    user_id BIGINT,
    PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_film_likes_film_id ON film_likes (film_id);
CREATE INDEX IF NOT EXISTS idx_film_likes_user_id ON film_likes (user_id);

CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT,
    friend_id BIGINT,
    status VARCHAR(10) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'CONFIRMED', 'REMOVED')),
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE,
    CHECK (user_id != friend_id)
);

CREATE INDEX IF NOT EXISTS idx_friendship_user_id ON friendship(user_id);
CREATE INDEX IF NOT EXISTS idx_friendship_friend_id ON friendship(friend_id);
CREATE TABLE IF NOT EXISTS directors (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS film_director (
                                             film_id BIGINT,
                                             director_id BIGINT,
                                             PRIMARY KEY (film_id, director_id),
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    FOREIGN KEY (director_id) REFERENCES directors(id) ON DELETE RESTRICT
    );

CREATE INDEX IF NOT EXISTS idx_film_director_film_id ON film_director(film_id);
CREATE INDEX IF NOT EXISTS idx_film_director_director_id ON film_director(director_id);
CREATE TABLE IF NOT EXISTS reviews
(
    review_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id     BIGINT  NOT NULL,
    user_id     BIGINT  NOT NULL,
    is_positive BOOLEAN NOT NULL,
    content     TEXT    NOT NULL,
    useful      INTEGER DEFAULT 0,
    CONSTRAINT uq_review_film_user UNIQUE (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviewRating
(
    user_id   BIGINT NOT NULL,
    review_id BIGINT NOT NULL,
    rating    INT    NOT NULL,
    PRIMARY KEY (user_id, review_id),
    FOREIGN KEY (user_id) REFERENCES users (id)  ON DELETE CASCADE,
    FOREIGN KEY (review_id) REFERENCES reviews (review_id)  ON DELETE CASCADE,
    CHECK (rating IN (-1, 1))
);

CREATE TABLE IF NOT EXISTS FeedEvents
(
    event_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp  BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    operation  VARCHAR(20) NOT NULL,
    entity_id  BIGINT      NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE,
    CHECK (event_type IN ('LIKE', 'REVIEW', 'FRIEND')),
    CHECK (operation IN ('REMOVE', 'ADD', 'UPDATE'))
);
